name: Build and Push to ECR

on:
  push:
    branches:
      - main   # trigger when push on main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to ECR # Login into ECR
        run: |
          aws ecr get-login-password --region us-east-1 \
          | docker login --username AWS --password-stdin 816069122835.dkr.ecr.us-east-1.amazonaws.com

      - name: Set Image tag
        run: echo "IMAGE_TAG=${GITHUB_SHA}" >> $GITHUB_ENV

      - name: Build Docker image
        run: docker build -t cloud-project-my-website:$IMAGE_TAG .

      - name: Tag image
        run: docker tag cloud-project-my-website:$IMAGE_TAG 816069122835.dkr.ecr.us-east-1.amazonaws.com/cloud-project-my-website:$IMAGE_TAG

      - name: Push to ECR
        run: docker push 816069122835.dkr.ecr.us-east-1.amazonaws.com/cloud-project-my-website:$IMAGE_TAG

      - name: Update ECS redeployment
        run: | 
          aws ecs update-service \
            --cluster my-cluster \
            --service my-service \
            --force-new-deployment
